export const recipeData = [
    {
        recipeName: "",
    },
    {
        recipeName: "Easy Brookie Pie",
        recipeSource: "https://www.melskitchencafe.com/brookie-pie/",
        recipeDescription: "This easy brookie pie is the perfect mashup of rich, decadent brownies and soft and chewy chocolate chip cookies! It’s easy and so very delicious!",
        ingredient1: "12 tablespoons butter",
        ingredient2: "2 cup chocolate chips",
        ingredient3: "2/3 cup granulated sugar",
        ingredient4: "3 large eggs",
        ingredient5: "2 tsp vanilla extract",
        ingredient6: "1 1/2 cup flour",
        ingredient7: "3 tbsp cocoa powder",
        ingredient8: "1/2 tsp salt",
        ingredient9: "1/3 cup brown sugar",
        ingredient10: "1/2 tsp baking soda",
    },
    {
        recipeName: "Avocado Chicken Salad",
        recipeSource: "https://www.melskitchencafe.com/avocado-chicken-salad/",
        recipeDescription: "This avocado chicken salad is irresistible! Perfect for a light, healthy dinner, it’s also delicious for a quick lunch or great for party food. Bonus: it comes together FAST (15 minutes or less)!",
        ingredient1: "3 tbsp lime or lemon juice",
        ingredient2: "2 tbsp olive oil",
        ingredient3: "1/2 tsp salt",
        ingredient4: "Pinch black pepper",
        ingredient5: "2 cups chopped, cooked chicken",
        ingredient6: "1 cup corn kernels",
        ingredient7: "2 medium/large ripe avocados, peeled and diced",
        ingredient8: "1/4 cup finely chopped red onion",
        ingredient9: "1/4 cup chopped fresh cilantro or parsley",
    },
    {
        recipeName: "Sweet and Spicy Pork and Pineapple Tacos",
        recipeSource: "https://www.melskitchencafe.com/sweet-and-spicy-pork-and-pineapple-tacos/",
        recipeDescription: "Look no further for delicious, tender, perfectly sweet and spicy bites of pork, put into in a delicious taco!",
        ingredient1: "2 lbs pork tenderloin, trimmed and cut into 1-inch cubes",
        ingredient2: "Salt and pepper",
        ingredient3: "1 tbsp oil",
        ingredient4: "4 garlic cloves, finely minced or pressed",
        ingredient5: "1 tsp ground cumin",
        ingredient6: "2 tsp chili powder",
        ingredient7: "Pinch of cayenne pepper",
        ingredient8: "1/4 cup pineapple juice",
        ingredient9: "2-3 tbsp chopped fresh cilantro",
        ingredient10: "Corn or flour tortillas"
    },
    {
        recipeName: "Easy Winter Fresh Fruit Salad",
        recipeSource: "https://www.melskitchencafe.com/winter-fresh-fruit-salad/",
        recipeDescription: "This winter fruit salad is as delicious as it is pretty. Made with seasonal fresh fruit (with a few options for canned fruit, too!), the quick and easy dressing adds the perfect touch of something special.",
        ingredient1: "1 cup fresh blueberries",
        ingredient2: "1 cup peeled and diced kiwi fruit",
        ingredient3: "1 cup mandarin oranges, drained, or fresh mandarin/navel orange segments",
        ingredient4: "1 cup diced apples or pears",
        ingredient5: "1 cup halved grapes",
        ingredient6: "1/2 cup pomegranate seeds",
        ingredient7: "1 tbsp honey",
        ingredient8: "2 tbsp orange juice",
        ingredient9: "Light pinch of cinnamon",
    },
]